### ISSUE TITLE
Add state_code conversion

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/strayr#3]
@MattCowgill this is still my favourite package on the Internet.

Can you/I add numeric state code conversion ([from the ABS](https://www.abs.gov.au/ausstats/abs@.nsf/Lookup/by%20Subject/1270.0.55.001~July%202016~Main%20Features~Australia%20(AUS)%20and%20State%20%7C%20Territory%20(S%7CT)~10017))

``` 
1 = NSW
2 = Vic
3 = Qld
4 = SA
5 = WA
6 = Tas
7 = NT
8 = ACT
9 = Other
```

THANKS

**Comment by MattCowgill** [comment]
yes but I'm gonna drop "Other"

**Comment by wfmackey** [comment]
Yeah cool sure just override the ABS.

**Comment by MattCowgill** [comment]
done. Note that if you're converting _to_ `code`, the results will be a character vector ("1", not 1). If you're converting from code it can be either numeric or character, as in `strayr(c(1, 2))` or `strayr(c("1", "2"))`
