### ISSUE TITLE
Maybe the matching is too fuzzy?

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/strayr#4]
(I know this is not the time because the world is on fire but you literally asked me to file an issue right now)

Matching is maybe too fuzzy. Eg:

```
 strayr::strayr("Total public hospitals")
[1] "Vic"
```
ALTHOUGH changing the default `max_dist` would not be backwards compatible I guess. Just noting it.

**Comment by MattCowgill** [comment]
FYI this now matches to "Tot". I've left the default `max_dist` at 0.4 but am open to changing it
