### ISSUE TITLE
Warn on 'Australia'

### ISSUE THREAD

**Issue by wfmackey** [MattCowgill/strayr#5]
When a character string is "Australia", `strayr` fuzzy matches to South Australia:

```
> strayr::strayr("Australia")
[1] "SA"
```
Probably better to 1) warn, 2) return `NA` or 3) return `"Aus"`.

**Comment by wfmackey** [comment]
Just got tripped up on this btw:

```
> strayr::strayr(c("Aus", "NSW", "Vic", "Qld", "WA", "SA", "Tas", "ACT", "NT", "OTH"))
 [1] "SA"  "NSW" "Vic" "Qld" "WA"  "SA"  "Tas" "ACT" "NT"  "SA" 
```

**Comment by MattCowgill** [comment]
I'll fix it right now

**Comment by wfmackey** [comment]
ty matt -- still the best thing you have ever donex

**Comment by MattCowgill** [comment]
I think I'll turn down the default `max_dist` -- to lower the threshold at which `strayr()` will return `NA` if a string is too far from any match
